### ISSUE TITLE
Improve UI of login and signup page

### ISSUE THREAD

**Issue by C-Anirudh** [C-Anirudh/chuck#7]
Currently the login and signup page look quite odd as both are placed at the centre of a wide bootstrap card, that spans the entire width of the screen. I guess it would look better if the bootstrap card was the exact size of the form and not the entire width of the screen. Any better UI design is also appreciated.

As this issue involves change in the UI, be sure to include screenshots/ screen-casts of the changes made.

**Comment by DanielBiegler** [comment]
Heyo, I'm interested in helping for Hacktoberfest! :)

How is this, do you like this?:
![image](https://user-images.githubusercontent.com/14810858/65994074-cef48400-e492-11e9-8f8a-eb1879545196.png)

**Comment by C-Anirudh** [comment]
@DanielBiegler Can this be done only for the login and signup page ? The home page looks kind of empty if the card fits exactly to text. But I guess it would look good for the forms.

**Comment by DanielBiegler** [comment]
Sure, I could add a new class for that purpose! Alright, lemme make a fork then you can check it out yourself! Be right back.

**Comment by DanielBiegler** [comment]
See #9
